name: lint
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "src/**"
      - "scripts/**"
      - "tests/**"
      - ".github/workflows/lint.yaml"
  pull_request:
    paths:
      - "src/**"
      - "scripts/**"
      - "tests/**"
      - ".github/workflows/lint.yaml"
jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: astral-sh/setup-uv@v1
      - name: Install dependencies
        run: uv sync --extra dev --extra ui
      - name: Run ruff
        run: uv run ruff check .
      - name: Run ruff format
        run: uv run ruff format --check --diff .
      - name: Run basedpyright
        run: uv run basedpyright .