# https://www.mkdocs.org/user-guide/deploying-your-docs/
# https://squidfunk.github.io/mkdocs-material/publishing-your-site/#with-github-actions
name: publish-docs
on:
  workflow_dispatch:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: astral-sh/setup-uv@v1
      - name: Install dependencies
        run: uv sync --extra dev
      - name: Deploy docs
        run: uv run mkdocs gh-deploy --force